import os
# go directory to directory gathering each index.md file and directory info

autogenerate = True

#todo: 
#	gather documentation
#	retrieve contents of index.md file
#   store documentation from commandline

def parsing(dir):
	if not os.path.isdir(dir):
		return {}
		#error: dir must be an existing directory
	else:
		output = {}
		for filename in os.listdir(dir):
			if filename == "index.md":
				output[filename] = "index.md" # replace with contents of index.md file
			elif os.path.isdir(dir+"/"+filename):
				output[filename] = parsing(dir+"/"+filename)

		if (not "index.md" in output) and (autogenerate == True):
			f = open(dir+"/index.md", "w+")
			f.close()
			output["index.md"] = "autogenerated file"
		return output

